version: "2"

run:
  timeout: 10m

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/larsks/kwctl
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false

linters:
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - unused
  settings:
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-specific: true
    revive:
      confidence: 0.1
    errcheck:
      exclude-functions:
        - os.Setenv
        - (*github.com/veandco/go-sdl2/sdl.Renderer).SetDrawColor
        - (*github.com/veandco/go-sdl2/sdl.Renderer).Clear
        - (*github.com/veandco/go-sdl2/sdl.Renderer).FillRect
        - (*github.com/veandco/go-sdl2/sdl.Renderer).DrawRect
        - (*github.com/veandco/go-sdl2/sdl.Renderer).SetDrawBlendMode
        - (*github.com/veandco/go-sdl2/sdl.Renderer).Destroy
        - (*github.com/veandco/go-sdl2/sdl.Window).Destroy
        - (*github.com/veandco/go-sdl2/sdl.Texture).Destroy
  enable:
    - bodyclose
    - errcheck
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace
