FROM docker.io/golang:1.25-trixie

RUN apt-get update && \
      DEBIAN_FRONTEND=noninteractive \
      apt-get -y install \
        build-essential \
        libsdl2-dev \
        libsdl2-ttf-dev \
        libdrm-dev \
        libgbm-dev \
        && apt-get clean

RUN mkdir -p /cache
ENV GOCACHE=/cache/build
ENV GOMODCACHE=/cache/mod
